title: Hey, Welcome to Adam Sroka's Website!
author: Adam Sroka
description: Adam's little piece of the Internet
site_favicon: favicon.ico
github_username: adam-sroka
show_excerpts: true
theme: jekyll-theme-cayman
